# -*- coding: utf-8 -*-
"""Transavia Sentiment Analyzer.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJfsW63kTZksxsxY6AFyvv6XWz4tXTjy

#Transavia Sentiment Analyzer.
"""

!pip install google-api-python-client vaderSentiment pandas matplotlib seaborn

"""
Transavia YouTube Comments Sentiment Analysis
----------------------------------------------
Scrapes comments from YouTube videos mentioning Transavia
and performs sentiment analysis using VADER.

Requirements:
    pip install google-api-python-client vaderSentiment pandas matplotlib seaborn

Setup:
    1. Go to https://console.cloud.google.com/
    2. Create a project → Enable "YouTube Data API v3"
    3. Create an API key (free, 10,000 units/day quota)
    4. Paste it below — no billing required for basic usage
"""

from googleapiclient.discovery import build
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

# ─────────────────────────────────────────────
# 1. YOUR API KEY — fill this in
# ─────────────────────────────────────────────
YOUTUBE_API_KEY = "Insert Your API Key Here"

# ─────────────────────────────────────────────
# 2. CONNECT TO YOUTUBE

# ─────────────────────────────────────────────
youtube = build("youtube", "v3", developerKey=YOUTUBE_API_KEY)

# ─────────────────────────────────────────────
# 3. SEARCH FOR TRANSAVIA VIDEOS
# ─────────────────────────────────────────────
def search_videos(query="Transavia", max_results=10):
    """Search YouTube for videos mentioning Transavia."""
    print(f"Searching YouTube for: '{query}' ...")

    response = youtube.search().list(
        q=query,
        part="snippet",
        maxResults=max_results,
        type="video",
        relevanceLanguage="en"

    ).execute()

    videos = []
    for item in response["items"]:
        videos.append({
            "video_id":    item["id"]["videoId"],
            "title":       item["snippet"]["title"],
            "channel":     item["snippet"]["channelTitle"],
            "published":   item["snippet"]["publishedAt"][:10],
            "description": item["snippet"]["description"]
        })

    print(f"  → {len(videos)} videos found.")
    return videos

# ─────────────────────────────────────────────
# 4. SCRAPE COMMENTS FROM EACH VIDEO
# ─────────────────────────────────────────────
def scrape_comments(video_id, max_comments=100):
    """Scrape top-level comments from a YouTube video."""

    comments = []
    try:
        request = youtube.commentThreads().list(
            part="snippet",
            videoId=video_id,
            maxResults=min(max_comments, 100),
            textFormat="plainText",
            order="relevance"
        )
        response = request.execute()

        for item in response.get("items", []):
            c = item["snippet"]["topLevelComment"]["snippet"]
            comments.append({
                "video_id":   video_id,
                "comment":    c["textDisplay"],
                "likes":      c["likeCount"],
                "date":       c["publishedAt"][:10]
            })
    except Exception as e:
        print(f"  ⚠ Could not fetch comments for video {video_id}: {e}")

    return comments

# ─────────────────────────────────────────────
# 5. SENTIMENT ANALYSIS WITH VADER

# ─────────────────────────────────────────────
def analyze_sentiment(df):
    """Apply VADER sentiment scoring to each comment."""
    analyzer = SentimentIntensityAnalyzer()

    def get_sentiment(text):
        scores   = analyzer.polarity_scores(text)
        compound = scores["compound"]
        if compound >= 0.05:
            label = "Positive"
        elif compound <= -0.05:
            label = "Negative"
        else:
            label = "Neutral"
        return pd.Series({
            "compound":  compound,
            "positive":  scores["pos"],
            "neutral":   scores["neu"],
            "negative":  scores["neg"],
            "sentiment": label
        })

    print("Running sentiment analysis ...")
    df[["compound", "positive", "neutral", "negative", "sentiment"]] = df["comment"].apply(get_sentiment)
    return df


# ─────────────────────────────────────────────
# 6. SUMMARY STATISTICS
# ─────────────────────────────────────────────
def print_summary(df, videos):
    print("\n─── Overall Sentiment Distribution ───")
    counts = df["sentiment"].value_counts()
    pcts   = df["sentiment"].value_counts(normalize=True) * 100
    summary = pd.DataFrame({"Count": counts, "Percent (%)": pcts.round(1)})
    print(summary.to_string())

    print(f"\n─── Average Compound Score: {df['compound'].mean():.3f} ───")
    print("  (Range: -1 = most negative, +1 = most positive)\n")

    print("─── Top 3 Most Positive Comments ───")
    for _, row in df.nlargest(3, "compound")[["comment", "compound"]].iterrows():
        print(f"  [{row['compound']:.2f}] {row['comment'][:100]}")

    print("\n─── Top 3 Most Negative Comments ───")
    for _, row in df.nsmallest(3, "compound")[["comment", "compound"]].iterrows():
        print(f"  [{row['compound']:.2f}] {row['comment'][:100]}")

# ─────────────────────────────────────────────
# 7. VISUALIZATIONS
# ─────────────────────────────────────────────
def plot_results(df, videos):
    fig, ax = plt.subplots(figsize=(6, 5))

    fig.suptitle("Transavia — YouTube Comments Sentiment Analysis",
                 fontsize=13, fontweight="bold")

    colors = {"Positive": "#2ecc71", "Neutral": "#95a5a6", "Negative": "#e74c3c"}

    counts = df["sentiment"].value_counts().reindex(["Positive", "Neutral", "Negative"])
    ax.bar(counts.index, counts.values,
           color=[colors[s] for s in counts.index], edgecolor="white", width=0.5)
    ax.set_title("Sentiment Distribution")
    ax.set_ylabel("Number of Comments")
    for i, v in enumerate(counts.values):
        ax.text(i, v + 1, str(v), ha="center", fontweight="bold")

    plt.tight_layout()
    plt.savefig("transavia_youtube_sentiment.png", dpi=150, bbox_inches="tight")
    print("Plot saved as transavia_youtube_sentiment.png")
    plt.show()

# ─────────────────────────────────────────────
# 8. MAIN
# ─────────────────────────────────────────────
if __name__ == "__main__":
    # Search for videos
    videos = search_videos(query="Transavia", max_results=10)

    # Scrape comments from each video
    all_comments = []
    for video in videos:
        print(f"  Fetching comments: {video['title'][:60]}...")
        comments = scrape_comments(video["video_id"], max_comments=100)
        all_comments.extend(comments)


    print(f"\nTotal comments collected: {len(all_comments)}")

    # Build DataFrame and run sentiment analysis
    df = pd.DataFrame(all_comments)
    df = analyze_sentiment(df)

    # Results
    print_summary(df, videos)
    plot_results(df, videos)

    # Save to CSV
    df.to_csv("transavia_youtube_sentiment.csv", index=False)
    print("Results saved to transavia_youtube_sentiment.csv")

